[package]
name = "fragment"
version = "0.3.1"
authors = ["Jordan MacDonald <jordan@wastedintelligence.com>"]
description = "Simple fragment/substring matching library"
repository = "https://github.com/jmacdonald/fragment"
keywords = ["fragment", "substring", "match"]
license = "MIT"
